name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # 允许手动触发工作流
  workflow_dispatch:

# 设置权限
permissions:
  contents: read
  pages: write
  id-token: write

# 确保只有一个部署任务同时运行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    # 数据处理步骤已移除，用户将直接更新 enhanced_processed_sentiment_data.csv
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    
    - name: Generate JSON from CSV
      run: |
        python generate_json_from_csv.py
     
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
     
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4